### ISSUE TITLE
Add "all posts tagged X" conditions

### ISSUE THREAD

**Issue by mattyza** [woothemes/woosidebars#2]
For example, "All posts tagged 'featured'" or "All posts tagged 'dogs'", using post tags.

WP.org forum reference: http://wordpress.org/support/topic/single-entries-of-tag?replies=2

**Comment by gene158** [comment]
Any ideas on when this will be implemented??? Thanks for this plugin!

**Comment by mattyza** [comment]
@gene158 This will be in version 1.4.0.
