### ISSUE TITLE
Woosidebars Text Widgets disappearing

### ISSUE THREAD

**Issue by nlocardi** [woothemes/woosidebars#32]
I'm using a Genesis theme with Woosidebars and Text widgets won't stay or appear when added to a custom widget area. Other widgets seem to be working, but Text widgets, the one I really need to use, disappear from the widget area after being added and show the default "This is the Primary Sidebar Widget Area. You can add content to this area by visiting your Widgets Panel and adding new widgets to this area." Text when I go to the page. 

Is this is a known issue?

**Comment by mattyza** [comment]
@nlocardi - I believe this is due to the known issue of a slug not being set for a custom widget area. If you click "Quick Edit" on a custom widget area, an the slug field is a number, please change this to text. This should remedy the issue. :)
