### ISSUE TITLE
Woo Conditions error.

### ISSUE THREAD

**Issue by dwainm** [woothemes/woosidebars#36]
Hi @mattyza , we got a few tickets with this error

```

Warning: Invalid argument supplied for foreach() in
woosidebars/classes/class-woo-conditions.php on line 396

```

https://woothemes.zendesk.com/agent/tickets/261071
https://woothemes.zendesk.com/agent/tickets/261047

**Comment by mattyza** [comment]
Thanks @dwainm. Checking now.

Seems an issue where a post has no tag. I've committed a fix.

**Comment by mattyza** [comment]
@dwainm Please test master and let me know. Should work fine. Works fine for me.
